### ISSUE TITLE
Avoid using with Laravel Lumen

### ISSUE THREAD

**Issue by TechKat** [tremby/laravel-queue-monitor#1]
The `composer.json` file requires `laravel/framework`, which deletes all the requirements for Lumen, and causes your application to not work.

**Comment by nullifiedaccount3** [comment]
Good point.

**Comment by tremby** [comment]
This package is called "laravel-queue-monitor". At no point in the docs do I suggest trying to use it with Lumen. I've never tried it with Lumen. Does it work, other than the dependency on `laravel/framework`?
