### ISSUE TITLE
Illuminate\Contracts\Queue\ShouldQueue

### ISSUE THREAD

**Issue by carloquilala** [tremby/laravel-queue-monitor#3]
Interface 'Illuminate\Contracts\Queue\ShouldQueue' not found in laravel 5.0

**Comment by tremby** [comment]
Laravel 5.0 is out of support. This is a bug in the requirements for this package. It should actually require at least Laravel 5.1. 5.1 was the first long-term support release.

**Comment by tremby** [comment]
Updated the requirements in ec18baf.
