### ISSUE TITLE
Does not work with Laravel 5.5

### ISSUE THREAD

**Issue by TimoStahl** [tremby/laravel-queue-monitor#5]
Upgrade notes:

Any fire methods present on your Artisan commands should be renamed to handle.

https://laravel.com/docs/5.5/upgrade

**Comment by tremby** [comment]
Thanks for this. I'm actually not using this package at present on any current projects, only legacy ones which are sticking with older versions of Laravel.

A working patch which is backwards-compatible with earlier versions of Laravel would be most welcome.

**Comment by tremby** [comment]
I heard today about [Laravel Horizon](https://laravel.com/docs/5.5/horizon) which is new with Laravel 5.5. Maybe that obsoletes my package for Laravel 5.5 and beyond? If you try it out, let me know what you find!

**Comment by interludic** [comment]
Laravel horizon is only for Redis connections

**Comment by tremby** [comment]
OK, I'll add that to the readme. Thanks.
